version: "3.9"
services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
    environment:
      BASE_PATH: localhost
  auth-service:
    build:
      context: ./auth-service # specify directory where local Dockerfile is located

  reverse-proxy:
    restart: "unless-stopped"
    ports:
      - 80:80
    volumes:
      - ./nginx/local_templates:/etc/nginx/templates

  certbot:
    entrypoint: ["echo", "certbot disabled"]
