version: "3.9"
services:
  app-service:
    container_name: app-service
    image: vinorelbine/rusty-next:latest
    restart: "always"
    environment:
      NEXT_PUBLIC_API_URL: http://auth-service:3000
    ports:
      - "8000:8000"

  auth-service:
    build:
      context: ./auth-service # specify directory where local Dockerfile is located
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"

  reverse-proxy:
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local_templates:/etc/nginx/templates
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
      NGINX_HTTPS_PORT: 443
      AUTH_SERVICE_PORT: 3000
      APP_SERVICE_PORT: 8000
      DOMAIN: rustyauth.com

  certbot:
    entrypoint: ["echo", "certbot disabled"]
