version: "3.9"
services:
  app-service:
    container_name: app-service
    image: vinorelbine/rusty-next:latest
    restart: "always"
    environment:
      NEXT_PUBLIC_API_URL: http://auth-service:8000
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_started
    networks:
      - cert-network

  auth-service:
    container_name: auth-service
    image: vinorelbine/rusty-auth:latest
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres.noadiwsilfsnfdwglydp:${POSTGRES_PASSWORD}@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
      REDIS_HOST_NAME: ${REDIS_HOST_NAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8000:8000"
    networks:
      - cert-network

networks:
  cert-network:
    driver: bridge
