app_address: "0.0.0.0:8000"
test_app_address: "127.0.0.1:0"
jwt_secret: eyCahwDXA3bL7IdHivRhu/GcZorc9abWxqDo13ef+Vk=

postgres:
  database_url: postgres://postgres.noadiwsilfsnfdwglydp:vf3BC0AvumArZR5q@aws-0-us-east-1.pooler.supabase.com:5432/postgres
  password: vf3BC0AvumArZR5q
redis:
  host_name: stable-stallion-32028.upstash.io
  password: AX0cAAIncDExZDM4OTQyOTZmOGI0YmYyYjM1M2YzYzcxMTFmZDVmYnAxMzIwMjg
  port: "6379"
