app_address: "0.0.0.0:8000"
test_app_address: "127.0.0.1:0"
jwt_secret: "bHMdG6Xy4CU1rizlLC6B9PJM8IlnKOfan6rllWZ+tCc="

postgres:
  database_url: "postgres://postgres:pass1234@localhost:5432"
  password: "pass1234"
redis:
  host_name: "localhost"
  password: ""
  port: "6379"
