name: Build, Test and Deploy to Prod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  APP_ENV: production
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.2-alpine
        # Environment variables scoped only for the `postgres` element
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass1234 // This is a placeholder
          POSTGRES_DB: postgres
        # When you map ports using the ports keyword, GitHub uses the --publish command to publish the container’s ports to the Docker host
        # Opens tcp port 5432 on the host and service container
        ports:
          - 5432:5432
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-1"

      - name: Write config.toml
        run: echo "${{ secrets.CONFIG_TOML }}" | base64 --decode > auth-service/src/config/production.toml

      - name: Set environment variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_HOST_NAME=${{ secrets.REDIS_HOST_NAME }}" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV

      - name: Cache dependencies for auth-service
        uses: actions/cache@v3
        with:
          path: |
            auth-service/.cargo
            auth-service/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('auth-service/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust for auth-service
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build and test auth-service code
        working-directory: ./auth-service
        run: |
          export JWT_SECRET=secret
          export DATABASE_URL=postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432
          cargo build --verbose
          cargo test --verbose

      - name: Install dependencies for app-service
        working-directory: ./app-service
        run: |
          npm install

      - name: Build app-service code
        working-directory: ./app-service
        run: |
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push app-service image to Docker Hub
        id: build-app-service-image
        run: |
          cd app-service
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://auth-service:3000 \
            -t ${{ env.DOCKER_HUB_USERNAME }}/rusty-next:app-service-${{ env.IMAGE_TAG }} \
            -t ${{ env.DOCKER_HUB_USERNAME }}/rusty-next:app-service-latest .
          docker push ${{ env.DOCKER_HUB_USERNAME }}/rusty-next:app-service-${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_HUB_USERNAME }}/rusty-next:app-service-latest

      - name: Build, tag, and push auth-service image to Docker Hub
        id: build-auth-service-image
        run: |
          cd auth-service
          docker build \
            --build-arg DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg SQLX_OFFLINE=${{ env.SQLX_OFFLINE }} \
            --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --build-arg REDIS_HOST_NAME=${{ secrets.REDIS_HOST_NAME }} \
            --build-arg REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} \
            --build-arg POSTMARK_AUTH_TOKEN=${{ secrets.POSTMARK_AUTH_TOKEN }} \
            -t ${{ env.DOCKER_HUB_USERNAME }}/auth-service:auth-service-${{ env.IMAGE_TAG }} \
            -t ${{ env.DOCKER_HUB_USERNAME }}/auth-service:auth-service-latest .
          docker push ${{ env.DOCKER_HUB_USERNAME }}/auth-service:auth-service-${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_HUB_USERNAME }}/auth-service:auth-service-latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      BASE_PATH: ${{ vars.BASE_PATH }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy configuration and compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            config.yaml
            compose.yml
          target: "~/"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~
            docker compose down
            docker compose pull
            docker compose up -d
